import type { Metadata } from "next";

import "./globals.css";
import StoreProvider from "@/components/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/mapillary-js@4.1.2/dist/mapillary.css"
          rel="stylesheet"
        />
        <script src="https://unpkg.com/mapillary-js@4.1.2/dist/mapillary.js"></script>
      </head>
      <StoreProvider>
        <body>
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
